/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 80023
 Source Host           : localhost:3306
 Source Schema         : Roezec

 Target Server Type    : MySQL
 Target Server Version : 80023
 File Encoding         : 65001

 Date: 27/04/2021 12:55:23
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;


TRUNCATE TABLE `paises`;

-- ----------------------------
-- Records of paises
-- ----------------------------
INSERT INTO `paises` VALUES (1, 'ANGOLA', 'LUANDA', 5);
INSERT INTO `paises` VALUES (2, 'ARGELIA', 'ARGEL', 5);
INSERT INTO `paises` VALUES (3, 'BENIN', 'PORTO-NOVO', 5);
INSERT INTO `paises` VALUES (4, 'BOTSUANA', 'GABERONES', 5);
INSERT INTO `paises` VALUES (5, 'BURKINA FASO', 'UAGADUGÚ', 5);
INSERT INTO `paises` VALUES (6, 'BURUNDI', 'BUYUMBURA', 5);
INSERT INTO `paises` VALUES (7, 'CABO VERDE', 'PRAIA', 5);
INSERT INTO `paises` VALUES (8, 'CAMERÚN', 'YAUNDÉ', 5);
INSERT INTO `paises` VALUES (9, 'CHAD', 'YAMENA', 5);
INSERT INTO `paises` VALUES (10, 'COMORAS', 'MORONI', 5);
INSERT INTO `paises` VALUES (11, 'COSTA DE MARFIL', 'YAMUSUKRO, ABIYÁN', 5);
INSERT INTO `paises` VALUES (12, 'EGIPTO', 'EL CAIRO', 5);
INSERT INTO `paises` VALUES (13, 'ERITREA', 'ASMARA', 5);
INSERT INTO `paises` VALUES (14, 'ETIOPÍA', 'ADÍS ABEBA', 5);
INSERT INTO `paises` VALUES (15, 'GABÓN', 'LIBREVILLE', 5);
INSERT INTO `paises` VALUES (16, 'GAMBIA', 'BANJUL', 5);
INSERT INTO `paises` VALUES (17, 'GHANA', 'ACCRA', 5);
INSERT INTO `paises` VALUES (18, 'GUINEA', 'CONAKRY', 5);
INSERT INTO `paises` VALUES (19, 'GUINEA ECUATORIAL', 'MALABO', 5);
INSERT INTO `paises` VALUES (20, 'GUINEA-BISSAU', 'BISSAU', 5);
INSERT INTO `paises` VALUES (21, 'KENIA', 'NAIROBI', 5);
INSERT INTO `paises` VALUES (22, 'LESOTO', 'MASERU', 5);
INSERT INTO `paises` VALUES (23, 'LIBERIA', 'MONROVIA', 5);
INSERT INTO `paises` VALUES (24, 'LIBIA', 'TRÍPOLI', 5);
INSERT INTO `paises` VALUES (25, 'MADAGASCAR', 'ANTANANARIVO', 5);
INSERT INTO `paises` VALUES (26, 'MALAUI', 'LILONGÜE', 5);
INSERT INTO `paises` VALUES (27, 'MALI', 'BAMAKO', 5);
INSERT INTO `paises` VALUES (28, 'MARRUECOS', 'RABAT', 5);
INSERT INTO `paises` VALUES (29, 'MAURICIO', 'PORT LOUIS', 5);
INSERT INTO `paises` VALUES (30, 'MAURITANIA', 'NUAKCHOT', 5);
INSERT INTO `paises` VALUES (31, 'MOZAMBIQUE', 'MAPUTO', 5);
INSERT INTO `paises` VALUES (32, 'NAMIBIA', 'WINDHOEK', 5);
INSERT INTO `paises` VALUES (33, 'NÍGER', 'NIAMEY', 5);
INSERT INTO `paises` VALUES (34, 'NIGERIA', 'ABUYA', 5);
INSERT INTO `paises` VALUES (35, 'REPÚBLICA CENTROAFRICANA', 'BANGUI', 5);
INSERT INTO `paises` VALUES (36, 'REPÚBLICA DEL CONGO', 'BRAZZAVILLE', 5);
INSERT INTO `paises` VALUES (37, 'REPÚBLICA DEMOCRÁTICA DEL CONGO', 'KINSHASA', 5);
INSERT INTO `paises` VALUES (38, 'REPÚBLICA SAHARAUI', 'EL AAIÚN', 5);
INSERT INTO `paises` VALUES (39, 'RUANDA', 'KIGALI', 5);
INSERT INTO `paises` VALUES (40, 'SANTO TOMÉ Y PRÍNCIPE', 'SANTO TOMÉ', 5);
INSERT INTO `paises` VALUES (41, 'SENEGAL', 'DAKAR', 5);
INSERT INTO `paises` VALUES (42, 'SEYCHELLES', 'VICTORIA', 5);
INSERT INTO `paises` VALUES (43, 'SIERRA LEONA', 'FREETOWN', 5);
INSERT INTO `paises` VALUES (44, 'SOMALIA', 'MOGADISCIO', 5);
INSERT INTO `paises` VALUES (45, 'SUAZILANDIA', 'MBABANE', 5);
INSERT INTO `paises` VALUES (46, 'SUD5', 'PRETORIA, CIUDAD DEL CABO, BLOEMFONTEIN', 5);
INSERT INTO `paises` VALUES (47, 'SUDÁN DEL NORTE', 'JARTUM', 5);
INSERT INTO `paises` VALUES (48, 'SUDÁN DEL SUR', 'YUBA', 5);
INSERT INTO `paises` VALUES (49, 'TANZANIA', 'DODOMA', 5);
INSERT INTO `paises` VALUES (50, 'TOGO', 'LOMÉ', 5);
INSERT INTO `paises` VALUES (51, 'TÚNEZ', 'TÚNEZ', 5);
INSERT INTO `paises` VALUES (52, 'UGANDA', 'KAMPALA', 5);
INSERT INTO `paises` VALUES (53, 'YIBUTI', 'YIBUTI', 5);
INSERT INTO `paises` VALUES (54, 'ZAMBIA', 'LUSAKA', 5);
INSERT INTO `paises` VALUES (55, 'ZIMBABUE', 'HARARE', 5);
INSERT INTO `paises` VALUES (56, 'ANTIGUA Y BARBUDA', 'SAINT JOHN\'S', 2);
INSERT INTO `paises` VALUES (57, 'ARGENTINA', 'BUENOS AIRES', 2);
INSERT INTO `paises` VALUES (58, 'BAHAMAS', 'NASSAU', 2);
INSERT INTO `paises` VALUES (59, 'BARBADOS', 'BRIDGETOWN', 2);
INSERT INTO `paises` VALUES (60, 'BELICE', 'BELMOPÁN', 2);
INSERT INTO `paises` VALUES (61, 'BOLIVIA', 'SUCRE, LA PAZ', 2);
INSERT INTO `paises` VALUES (62, 'BRASIL', 'BRASILIA', 2);
INSERT INTO `paises` VALUES (63, 'CANADÁ', 'OTTAWA', 2);
INSERT INTO `paises` VALUES (64, 'CHILE', 'SANTIAGO DE CHILE', 2);
INSERT INTO `paises` VALUES (65, 'COLOMBIA', 'BOGOTÁ', 2);
INSERT INTO `paises` VALUES (66, 'COSTA RICA', 'SAN JOSÉ', 2);
INSERT INTO `paises` VALUES (67, 'CUBA', 'LA HABANA', 2);
INSERT INTO `paises` VALUES (68, 'DOMINICA', 'ROSEAU', 2);
INSERT INTO `paises` VALUES (69, 'ECUADOR', 'QUITO', 2);
INSERT INTO `paises` VALUES (70, 'EL SALVADOR', 'SAN SALVADOR', 2);
INSERT INTO `paises` VALUES (71, 'ESTADOS UNIDOS', 'WASHINGTON D. C.', 2);
INSERT INTO `paises` VALUES (72, 'GRANADA', 'SAINT GEORGE\'S', 2);
INSERT INTO `paises` VALUES (73, 'GUATEMALA', 'CIUDAD DE GUATEMALA', 2);
INSERT INTO `paises` VALUES (74, 'GUYANA', 'GEORGETOWN', 2);
INSERT INTO `paises` VALUES (75, 'HAITÍ', 'PUERTO PRÍNCIPE', 2);
INSERT INTO `paises` VALUES (76, 'HONDURAS', 'TEGUCIGALPA', 2);
INSERT INTO `paises` VALUES (77, 'JAMAICA', 'KINGSTON', 2);
INSERT INTO `paises` VALUES (78, 'MÉXICO', 'MÉXICO D. F.', 2);
INSERT INTO `paises` VALUES (79, 'NICARAGUA', 'MANAGUA', 2);
INSERT INTO `paises` VALUES (80, 'PANAMÁ', 'CIUDAD DE PANAMÁ', 2);
INSERT INTO `paises` VALUES (81, 'PARAGUAY', 'ASUNCIÓN', 2);
INSERT INTO `paises` VALUES (82, 'PERÚ', 'LIMA', 2);
INSERT INTO `paises` VALUES (83, 'PUERTO RICO', 'SAN JUAN', 2);
INSERT INTO `paises` VALUES (84, 'REPÚBLICA DOMINICANA', 'SANTO DOMINGO', 2);
INSERT INTO `paises` VALUES (85, 'SAN CRISTÓBAL Y NIEVES', 'BASSETERRE', 2);
INSERT INTO `paises` VALUES (86, 'SAN VICENTE Y LAS GRANADINAS', 'KINGSTOWN', 2);
INSERT INTO `paises` VALUES (87, 'SANTA LUCÍA', 'CASTRIES', 2);
INSERT INTO `paises` VALUES (88, 'SURINAM', 'PARAMARIBO', 2);
INSERT INTO `paises` VALUES (89, 'TRINIDAD Y TOBAGO', 'PUERTO ESPAÑA', 2);
INSERT INTO `paises` VALUES (90, 'URUGUAY', 'MONTEVIDEO', 2);
INSERT INTO `paises` VALUES (91, 'VENEZUELA', 'CARACAS', 2);
INSERT INTO `paises` VALUES (92, 'AFGANISTÁN', 'KABUL', 3);
INSERT INTO `paises` VALUES (93, 'ARABIA SAUDITA', 'RIAD', 3);
INSERT INTO `paises` VALUES (94, 'BANGLADÉS', 'DACA', 3);
INSERT INTO `paises` VALUES (95, 'BARÉIN', 'MANAMÁ', 3);
INSERT INTO `paises` VALUES (96, 'BRUNEI', 'BANDAR SERI BEGAWAN', 3);
INSERT INTO `paises` VALUES (97, 'BUTÁN', 'TIMBU', 3);
INSERT INTO `paises` VALUES (98, 'CAMBOYA', 'PNON PEHN', 3);
INSERT INTO `paises` VALUES (99, 'CATAR', 'DOHA', 3);
INSERT INTO `paises` VALUES (100, 'CHINA', 'PEKÍN', 3);
INSERT INTO `paises` VALUES (101, 'CHIPRE', 'NICOSIA', 3);
INSERT INTO `paises` VALUES (102, 'COREA DEL NORTE', 'PYONGYANG', 3);
INSERT INTO `paises` VALUES (103, 'COREA DEL SUR', 'SEÚL', 3);
INSERT INTO `paises` VALUES (104, 'EMIRATOS ARABES UNIDOS', 'ABU DABI', 3);
INSERT INTO `paises` VALUES (105, 'FILIPINAS', 'MANILA', 3);
INSERT INTO `paises` VALUES (106, 'INDIA', 'NUEVA DELHI', 3);
INSERT INTO `paises` VALUES (107, 'INDONESIA', 'YAKARTA', 3);
INSERT INTO `paises` VALUES (108, 'IRÁN', 'TEHERÁN', 3);
INSERT INTO `paises` VALUES (109, 'IRAQ', 'BAGDAD', 3);
INSERT INTO `paises` VALUES (110, 'ISRAEL', 'JERUSALÉN', 3);
INSERT INTO `paises` VALUES (111, 'JAPÓN', 'TOKIO', 3);
INSERT INTO `paises` VALUES (112, 'JORDANIA', 'AMMÁN', 3);
INSERT INTO `paises` VALUES (113, 'KAZAJISTÁN', 'ASTANÁ', 3);
INSERT INTO `paises` VALUES (114, 'KIRGUISTÁN', 'BISKEK', 3);
INSERT INTO `paises` VALUES (115, 'KUWAIT', 'CIUDAD DE KUWAIT', 3);
INSERT INTO `paises` VALUES (116, 'LAOS', 'VIENTIÁN', 3);
INSERT INTO `paises` VALUES (117, 'LÍBANO', 'BEIRUT', 3);
INSERT INTO `paises` VALUES (118, 'MAL3', 'KUALA LUMPUR', 3);
INSERT INTO `paises` VALUES (119, 'MALDIVAS', 'MALÉ', 3);
INSERT INTO `paises` VALUES (120, 'MONGOLIA', 'ULAN BATOR', 3);
INSERT INTO `paises` VALUES (121, 'MYANMAR (BIRMANIA)', 'NAYPYIDAW', 3);
INSERT INTO `paises` VALUES (122, 'NEPAL', 'KATMANDÚ', 3);
INSERT INTO `paises` VALUES (123, 'OMÁN', 'MASCATE', 3);
INSERT INTO `paises` VALUES (124, 'PAKISTÁN', 'ISLAMABAD', 3);
INSERT INTO `paises` VALUES (125, 'PALESTINA', 'RAMALA', 3);
INSERT INTO `paises` VALUES (126, 'SINGAPUR', 'SINGAPUR', 3);
INSERT INTO `paises` VALUES (127, 'SIRIA', 'DAMASCO', 3);
INSERT INTO `paises` VALUES (128, 'SRI LANKA', 'COLOMBO', 3);
INSERT INTO `paises` VALUES (129, 'TAILANDIA', 'BANGKOK', 3);
INSERT INTO `paises` VALUES (130, 'TAIWAN', 'TAIPEH', 3);
INSERT INTO `paises` VALUES (131, 'TAYIKISTÁN', 'DUSAMBÉ', 3);
INSERT INTO `paises` VALUES (132, 'TIMOR ORIENTAL', 'DILI', 3);
INSERT INTO `paises` VALUES (133, 'TURKMENISTÁN', 'ASJABAD', 3);
INSERT INTO `paises` VALUES (134, 'TURQUÍA', 'ANKARA', 3);
INSERT INTO `paises` VALUES (135, 'UZBEKISTÁN', 'TASHKENT', 3);
INSERT INTO `paises` VALUES (136, 'VIETNAM', 'HANOI', 3);
INSERT INTO `paises` VALUES (137, 'YEMEN', 'SANÁ', 3);
INSERT INTO `paises` VALUES (138, 'ALBANIA', 'TIRANA', 1);
INSERT INTO `paises` VALUES (139, 'ALEMANIA', 'BERLÍN', 1);
INSERT INTO `paises` VALUES (140, 'ANDORRA', 'ANDORRA LA VIEJA', 1);
INSERT INTO `paises` VALUES (141, 'ARMENIA', 'EREVÁN', 1);
INSERT INTO `paises` VALUES (142, 'AUSTRIA', 'VIENA', 1);
INSERT INTO `paises` VALUES (143, 'AZERBAIYÁN', 'BAKÚ', 1);
INSERT INTO `paises` VALUES (144, 'BÉLGICA', 'BRUSELAS', 1);
INSERT INTO `paises` VALUES (145, 'BIELORRUSIA', 'MINSK', 1);
INSERT INTO `paises` VALUES (146, 'BOSNIA Y HERZEGOVINA', 'SARAJEVO', 1);
INSERT INTO `paises` VALUES (147, 'BULGARIA', 'SOFÍA', 1);
INSERT INTO `paises` VALUES (148, 'CROACIA', 'ZAGREB', 1);
INSERT INTO `paises` VALUES (149, 'DINAMARCA', 'COPENHAGUE', 1);
INSERT INTO `paises` VALUES (150, 'ESLOVAQUIA', 'BRATISLAVA', 1);
INSERT INTO `paises` VALUES (151, 'ESLOVENIA', 'LUBLIJANA', 1);
INSERT INTO `paises` VALUES (152, 'ESPAÑA', 'MADRID', 1);
INSERT INTO `paises` VALUES (153, 'ESTONIA', 'TALLÍN', 1);
INSERT INTO `paises` VALUES (154, 'FINLANDIA', 'HELSINKI', 1);
INSERT INTO `paises` VALUES (155, 'FRANCIA', 'PARÍS', 1);
INSERT INTO `paises` VALUES (156, 'GEORGIA', 'TIFLIS', 1);
INSERT INTO `paises` VALUES (157, 'GRECIA', 'ATENAS', 1);
INSERT INTO `paises` VALUES (158, 'HUNGRÍA', 'BUDAPEST', 1);
INSERT INTO `paises` VALUES (159, 'IRLANDA', 'DUBLÍN', 1);
INSERT INTO `paises` VALUES (160, 'ISLANDIA', 'REIKIAVIK', 1);
INSERT INTO `paises` VALUES (161, 'ITALIA', 'ROMA', 1);
INSERT INTO `paises` VALUES (162, 'LETONIA', 'RIGA', 1);
INSERT INTO `paises` VALUES (163, 'LIECHTENSTEIN', 'VADUZ', 1);
INSERT INTO `paises` VALUES (164, 'LITUANIA', 'VILNA', 1);
INSERT INTO `paises` VALUES (165, 'LUXEMBURGO', 'LUXEMBURGO', 1);
INSERT INTO `paises` VALUES (166, 'MALTA', 'LA VALETA', 1);
INSERT INTO `paises` VALUES (167, 'MOLDAVIA', 'CHISINAU', 1);
INSERT INTO `paises` VALUES (168, 'MÓNACO', 'MÓNACO', 1);
INSERT INTO `paises` VALUES (169, 'MONTENEGRO', 'PODGORICA', 1);
INSERT INTO `paises` VALUES (170, 'NORUEGA', 'OSLO', 1);
INSERT INTO `paises` VALUES (171, 'PAÍSES BAJOS', 'AMSTERDAM', 1);
INSERT INTO `paises` VALUES (172, 'POLONIA', 'VARSOVIA', 1);
INSERT INTO `paises` VALUES (173, 'PORTUGAL', 'LISBOA', 1);
INSERT INTO `paises` VALUES (174, 'REINO UNIDO', 'LONDRES', 1);
INSERT INTO `paises` VALUES (175, 'REPÚBLICA CHECA', 'PRAGA', 1);
INSERT INTO `paises` VALUES (176, 'REPÚBLICA DE MACEDONIA', 'SKOPJE', 1);
INSERT INTO `paises` VALUES (177, 'RUMANIA', 'BUCAREST', 1);
INSERT INTO `paises` VALUES (178, 'RUSIA', 'MOSCÚ', 1);
INSERT INTO `paises` VALUES (179, 'SAN MARINO', 'CIUDAD DE SAN MARINO', 1);
INSERT INTO `paises` VALUES (180, 'SERBIA', 'BELGRADO', 1);
INSERT INTO `paises` VALUES (181, 'SUECIA', 'ESTOCOLMO', 1);
INSERT INTO `paises` VALUES (182, 'SUIZA', 'BERNA', 1);
INSERT INTO `paises` VALUES (183, 'UCRANIA', 'KIEV', 1);
INSERT INTO `paises` VALUES (184, 'VATICANO', 'CIUDAD DEL VATICANO', 1);
INSERT INTO `paises` VALUES (185, 'AUSTRALIA', 'CANBERRA', 4);
INSERT INTO `paises` VALUES (186, 'FIYI', 'SUVA', 4);
INSERT INTO `paises` VALUES (187, 'ISLAS MARSHALL', 'MAJURO', 4);
INSERT INTO `paises` VALUES (188, 'ISLAS SALOMÓN', 'HONIARA', 4);
INSERT INTO `paises` VALUES (189, 'KIRIBATI', 'TARAWA', 4);
INSERT INTO `paises` VALUES (190, 'MICRONESIA', 'PALIKIR', 4);
INSERT INTO `paises` VALUES (191, 'NAURU', 'YAREN', 4);
INSERT INTO `paises` VALUES (192, 'NUEVA ZELANDA', 'WELLINGTON', 4);
INSERT INTO `paises` VALUES (193, 'PALAOS', 'MELEKEOK', 4);
INSERT INTO `paises` VALUES (194, 'PAPÚA NUEVA GUINEA', 'PORT MORESBY', 4);
INSERT INTO `paises` VALUES (195, 'SAMOA', 'APIA', 4);
INSERT INTO `paises` VALUES (196, 'TONGA', 'NUKU\'ALOFA', 4);
INSERT INTO `paises` VALUES (197, 'TUVALU', 'FUNAFUTI', 4);
INSERT INTO `paises` VALUES (198, 'VANUATU', 'PORT VILA', 4);

SET FOREIGN_KEY_CHECKS = 1;
